##################################################
#
# Name: dependabot.yml
# Description: Dependabot configuration for GitHub native version
# Reference: https://git.io/JJhjE
#
##################################################

version: 2

updates: {}

